version: '3.3'

services:
  application:
    image: east-trade-image
    user: root
    container_name: east-trade-container-1
    ports:
      - "80:8080"
    depends_on:
      - database
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/east-trade"
      - "SPRING_DATASOURCE_USERNAME=postgres"
      - "SPRING_DATASOURCE_PASSWORD=qwerty007"
      - "SERVER_PORT=8080"
    networks:
      - cloud

  database:
    image: postgres
    container_name: postgres-container-1
    ports:
      - "5431:5432"
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty007
      - POSTGRES_DB=east-trade
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - cloud

volumes:
  postgres_volume:
    external: true

networks:
  cloud:
    external: true