GET localhost:80/api/articles/3

###

DELETE localhost:80/api/articles/11

###

POST localhost:80/api/create-article
Content-Type: application/json

{
  "title": "Тест из REST API!",
  "content": "<p>Тест запроса на создание статьи!</p>",
  "publishDate": "2023-05-21T10:11:38.874+00:00",
  "accountEmail": "Timerhelmut@gmail.com",
  "accountInfo": "Bulat Gilmutdinov"
}

###

POST http://localhost:80/registration
Content-Type: application/x-www-form-urlencoded

email=example@gmail.com&password=12345678

###

POST http://localhost:80/login
Content-Type: application/x-www-form-urlencoded

email=Timerhelmut@gmail.com&password=123